name: Build DevOps NodeJs Agent Image.

on: workflow_dispatch

jobs:
  buildAgent:
    uses: ./.github/workflows/buildAgent.yml
    with:
      suffix: nodejs
      workingDirectory: ./ubuntu20.04-nodejs
